### ISSUE TITLE
TypeError: Argument 'normal_bam' has incorrect type (expected csamtools.Samfile, got pysam.csamtools.Samfile)

### ISSUE THREAD

**Issue by mortunco** [mortunco/joint-snv-mix#24]
Hi,

I am trying to run JointSNVmix2 version 0.7.5. I got the following error. Indepenent from the normal bam file ( i tried to change to tumor also) gave the same output. Please help me.

my pysam version is 0.5.

```
Tuncs-MacBook-Pro:blackhole morova$ python ~/JointSNVMix-0.7.5/build/scripts-2.7/jsm.py train joint_snv_mix_two --convergence_threshold 0.01 reference/Homo_sapiens_assembly19.fasta tumor/TCGA-CH-5741-01A-11D-1572_130104_SN1120_0209_BD1KP6ACXX_s_1_rg.sorted.bam tumor/TCGA-CH-5741-01A-11D-1572_130104_SN1120_0209_BD1KP6ACXX_s_1_rg.sorted.bam ~/JointSNVMix-0.7.5/config/joint_priors.cfg ~/JointSNVMix-0.7.5/config/joint_params.cfg jointsnvmix2/joinsnvmix_newparams.txt
Traceback (most recent call last):
  File "/Users/morova/JointSNVMix-0.7.5/build/scripts-2.7/jsm.py", line 224, in <module>
    args.func(args)
  File "/usr/local/lib/python2.7/site-packages/joint_snv_mix/runners/train.py", line 52, in joint_snv_mix_two_train
    counter = get_qual_counter(args)
  File "/usr/local/lib/python2.7/site-packages/joint_snv_mix/runners/train.py", line 84, in get_qual_counter
    counter = JointBinaryQualityCounter(normal_bam, tumour_bam, ref_genome)
  File "joint_binary_quality_counter.pyx", line 13, in joint_snv_mix.counters.joint_binary_quality_counter.JointBinaryQualityCounter.__init__ (joint_snv_mix/counters/joint_binary_quality_counter.c:1309)
TypeError: Argument 'normal_bam' has incorrect type (expected csamtools.Samfile, got pysam.csamtools.Samfile)
```

**Comment by mortunco** [comment]
I also got the same error when I call jsm.py from the system. Without python jsm.py. Just jsm.py.

**Comment by mortunco** [comment]
Apparently It was about pysam version. I previously have downloaded MACE library with pip. Therefore, python used to take pysam from that folder. When I delete the MACE lib, it solved my problem. It should be investigated though.
